---
title: "Regex in R"
output: html_document
---


## Cheatcode


| Syntax     | Description                                           |
|----------- |-------------------------------------------------------|
| \\d        | Digit 0:9                                             |
| \\D        | Non Digit                                             |
| \\s        | Space                                                 |
| \\S        | Not Space                                             |
| \\w        | Word                                                  |
|[A-Za-z0-9_]| Word                                                  |
| \\W        | Not Word                                              |
| \\t        | Tab                                                   |
|  \\n       | New Line                                              |
| \\b        | Word Boundary                                         |
| \\B        | Non-word Boundary                                     |
| ^          | Beginning of String                                   |
| $          | End of String                                         |
|  |         | Alternation Match e.g.,/(i|o)n/ matches "in" and "on" |
|  .         | Any character                                         |
|  \\.       | Matches "." literally                                 |
|  [ab]      | Matches a or b literally                              |
|  [^ab]     | Any character except a and b                          |
|  [0-9]     | All digit                                             |
|  [A-Z]     | All uppercase A to Z letters                          |
|  [a-z]     | All lowercase A to Z letters                          |
|  +         | At least one time                                     |
|  *         | Zero or more times                                    |
|  ?         | Zero or one  times                                    |
|  {n}       | Occurs n times                                        |
| {n1,n2}    | Occurs n1-n2 times                                    |
|{n1,n2}?    | non greedy match                                      |
|  {n,}      | ocurrs >= n times                                     |
|[:alnum:]   | Alphanumeric characters                               |
|[:alpha:]   | Alphabetic characters                                 |
|[:blank:]   | Blank characters                                      |
|[:digit:]   | Digits 0:9                                            |
|[:graph:]   | Graphical characters                                  |
|[:punct:]   | Punctuation character                                 |
|[:space:]   | Space characters                                      |
|[:upper:]   | Upper-case letters                                    |
|[:xdigit:]  | Hexadecimal digits                                    |



